language: python
python:
- '3.4'
- '3.5'
- '2.7'
install:
- pip install -r tests/requirements.txt
script:
- coverage run runtests.py
after_success:
- codecov
deploy:
  provider: pypi
  user: Christian.Ledermann
  password:
    secure: F6E00cC2xCIRhBVh9L2p1k9joBYNRgCPIFy9ckFhcVgGhuTXZ9xbJrMap+EN9OIVdok2zGpJycgONKdNeYrQgIv2KzWrmg1uwcLuErHtEAJPIqi7ES2pyGXZCnpcN0iguAptthOtw7wBgxroW3cf0Wixs+wliN9U/ab5MYrQHou8I1pzRCwlp1aKPVxRJF/DavIkC16nU6arCX2YS2nmGNywlvScs+Gd51EJjC326iDeHjYfkSFmFRtGQ9Bn1fsH6JUoio0MG9wvz3ItqU4ceoXcQJLVB0i1uKyoM1r7Yml8X/PwLJaRnvs60RdBgvrEw0uuO9yVUzZmOuE64T9fK/UhAIBwcjsh24HuXJHw6civECtQ2CgsThyXNIzWhX7QFy78F+B8Z4S6sAJDdkrPo8XXFMW+KIFIBNiZF2cBUGzsmr5dd4DmDNky3Yb0SknRQPg3nVtA66CQGDWob/T9A5QJ+y1f139zgvcwncABVgo8Zesp1eJnp2MgYUivgsFdxI/SL7WzSF9osPe24FsYIfVHB01XGeYizvapexNEQmJve606Scgl8hXXuTgP1lIAzWKX9DRMKK29y1+AGVxek5PXzuPr+LmYvEWISq2Cq/Lhu3qmnPPjpdq5zAIznRQ3XPoZ+l18dXRh7QAXGcQlmRcsFVAuxAcjl0V8/GD3rZk=
  on:
    branch: master
