[tool.black]
line-length = 99
target-version = ['py37', ]
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
    \.pytest_cache
    node_modules
    .cache
  | _build
  | buck-out
  | build
  | dist
)/
'''
