---
version: 2
jobs:
  test-static:
    docker:
      - image: circleci/python:3.7
        user: circleci
    steps:
      - checkout
      - run:
          name: Ruff - (Black, flake8, Isort)
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements/flake8.txt
            pip install -r requirements/requirements-dj22.txt
            ruff --version
            ruff check --extend-exclude=migrations \
              $(git diff --diff-filter=d \
              --name-only origin/develop..HEAD -- '*.py')
      - run:
          name: Linting bandit/yaml
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements/flake8.txt
            pip install -r requirements/requirements-dj22.txt
            bandit -r drfdapc
            yamllint .circleci
      - run:
          name: pip-check
          command: |
            source venv/bin/activate
            pip-check -a
      - run:
          name: mypy
          command: |
            source venv/bin/activate
            mypy drfdapc
      - run:
          name: Complexity
          command: |
            source venv/bin/activate
            echo '----------Cyclomatic complexity -----------'
            radon cc --min B --average --total-average drfdapc
            echo '----------Maintainability Index-----------'
            radon mi --min B  drfdapc
            echo '-----------Lizard Cyclomatic Complexity for python---------'
            lizard  -l python -w drfdapc

  test-django-2.2-py-3.7:
    docker:
      - image: circleci/python:3.7
        user: circleci
    steps:
      - checkout
      - run:
          name: Django 2.2 with Python 3.7
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements/requirements-dj22.txt
            pytest drfdapc --cov=drdapc
            codecov --token=d1a7380f-e48e-4280-80b5-9004a70e935b


workflows:
  version: 2
  build-and-test:
    jobs:
      - test-django-2.2-py-3.7
      - test-static
...
